name: com_gen
channels:
  - defaults
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - aster=1.23=h9948957_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottle=0.13.2=py314h06a4308_0
  - bottleneck=1.4.2=py314h6a40391_1
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - brotli-python=1.2.0=py314h3dd09e2_0
  - brotlicffi=1.0.9.2=py314hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cd-hit=4.6.8=hfc679d8_2
  - cffi=2.0.0=py314h4eded50_1
  - charset-normalizer=3.4.4=py314h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py314hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py314hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - dendropy=5.0.8=pyhdfd78af_1
  - ete3=3.1.3=pyhd8ed1ab_0
  - ete4=4.3.0=py314h5bd0f2a_1
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py314hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gawk=5.3.1=h5eee18b_0
  - gettext=0.21.0=hedfda30_2
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py314h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - iqtree=2.1.4_beta=hdcc8f71_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.8=py314h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libcups=2.4.2=h252cb56_2
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - lmdb=0.9.31=hb25bd0a_0
  - lxml=5.3.0=py314h41e9850_1
  - lz4-c=1.9.4=h6a678d5_1
  - mafft=7.505=hec16e2b_0
  - matplotlib-base=3.10.6=py314haca3bed_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mesalib=25.1.5=h31e3550_0
  - mmseqs2=13.45111=h95f258a_1
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - ncbi-datasets-cli=18.14.0=ha770c72_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py314h4c79f44_0
  - numpy=2.3.4=py314h8d14b15_1
  - numpy-base=2.3.4=py314h8dfe1fa_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha0b5721_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py314h3b88751_1
  - pip=25.2=pyh0d26453_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py314hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py314h06a4308_0
  - pyqt=6.9.1=py314h43fb04a_0
  - pyqt6-sip=13.10.2=py314hee96239_0
  - pysocks=1.7.1=py314h06a4308_1
  - python=3.14.0=h3fc5862_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=1_cp314
  - pytz=2025.2=py314h06a4308_0
  - pyzmq=27.1.0=py314hcf8288c_1
  - qtbase=6.9.2=hd13baf8_4
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_0
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py314h06a4308_1
  - scipy=1.16.2=py314hcebf877_0
  - seaborn=0.13.2=py314h06a4308_3
  - setuptools=80.9.0=py314h06a4308_0
  - sip=6.12.0=py314h695c4d2_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py314h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py314h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wget=1.25.0=he4200e1_2
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xextproto=7.3.0=h5eee18b_1004
  - xorg-xorgproto=2024.1=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anyio==4.11.0
      - bio==1.8.1
      - biopython==1.86
      - biothings-client==0.4.1
      - certifi==2025.10.5
      - gprofiler-official==1.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jamsfetch==1.0.3
      - mygene==3.2.2
      - pooch==1.8.2
      - sniffio==1.3.1
      - tqdm==4.67.1

